Repository ToTee-Block/Main, pull requests merged in 2024-11, with the labels that each got.

#8 Member엔티티 수정, 사진 업로드 완료, 프로필 수정 완료
  src/main/java/com/example/Main/domain/Member/controller/ApiV1MemberController.java
  src/main/java/com/example/Main/domain/Member/dto/MemberDTO.java
  src/main/java/com/example/Main/domain/Member/entity/Member.java
  src/main/java/com/example/Main/domain/Member/request/MemberCreate.java
  src/main/java/com/example/Main/domain/Member/service/MemberService.java
  src/main/java/com/example/Main/global/InitData/Init.java
Labels: enhancement

#10 frontend 변경사항
  frontend/src/app/about/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/member/page.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/button/TextLinkButton.tsx
  frontend/styles/components/button/text-link-button.module.scss
  frontend/styles/main.scss
  frontend/styles/pages/about.scss
  frontend/styles/pages/home.scss
  frontend/styles/pages/join.scss
  frontend/styles/pages/login.module.scss
  package-lock.json
  package.json
Labels: bug

#13 Create 기본-이슈-템플릿
  .github/ISSUE_TEMPLATE/기본-이슈-템플릿
Labels: documentation

#11 회원 / (프론트) 로그인 / 박승수
  frontend/public/icon/close_eye.svg
  frontend/public/icon/open_eye.svg
  frontend/public/icon/yellow_botton.svg
  frontend/src/app/member/join/page.tsx
  frontend/src/app/member/page.tsx
  frontend/src/components/button/Loginbutton.tsx
  frontend/src/components/input/TextInput.tsx
  frontend/styles/components/button/login-button.module.scss
  frontend/styles/components/input/text-input.module.scss
  frontend/styles/globals/color.scss
  frontend/styles/pages/join.scss
  frontend/styles/pages/login.module.scss
  frontend/styles/pages/member/login.module.scss
Labels: enhancement

#17 [이슈]기반 소스
  .github/ISSUE_TEMPLATE/-이슈--이슈-내용-작성자.md
Labels: enhancement

#19 회원 / 회원가입(프론트) / 박승수
  frontend/public/icon/yellow_botton.svg
  frontend/src/app/member/join/page.tsx
  frontend/src/components/birthday/Birthday.tsx
  frontend/src/components/button/GenderButton.tsx
  frontend/src/components/input/TextInput.tsx
  frontend/styles/components/birthday/birthday.module.scss
  frontend/styles/components/button/gender-button.module.scss
  frontend/styles/components/button/login-button.module.scss
  frontend/styles/components/input/text-input.module.scss
  frontend/styles/globals/font.scss
  frontend/styles/pages/member/join.module.scss
Labels: enhancement

#18 Member/01~04/리팩토링, 예외처리, JWT & SpringSecurity 같이 사용하기
  backend/src/main/java/com/example/Main/domain/Member/controller/ApiV1MemberController.java
  backend/src/main/java/com/example/Main/domain/Member/repository/MemberRepository.java
  backend/src/main/java/com/example/Main/domain/Member/service/MemberService.java
  backend/src/main/java/com/example/Main/global/Jwt/JwtProvider.java
  backend/src/main/java/com/example/Main/global/Security/ApiSecurityConfig.java
  backend/src/main/java/com/example/Main/global/Security/JwtAuthorizationFilter.java
Labels: bug

#21 연동 / 프론트, 백 연동 성공 / 박승수
  backend/src/main/java/com/example/Main/MainApplication.java
  backend/src/main/java/com/example/Main/domain/Member/service/MemberService.java
  backend/src/main/java/com/example/Main/global/Security/ApiSecurityConfig.java
  backend/src/main/java/com/example/Main/global/Security/SecurityConfig.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/axiosConfig.ts
  frontend/src/app/member/join/page.tsx
  frontend/src/app/member/page.tsx
  frontend/src/app/members/form/page.tsx
  frontend/src/app/members/join/page.tsx
  frontend/src/app/members/me/page.tsx
  frontend/src/app/members/page.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/birthday/Birthday.tsx
  frontend/src/components/button/GenderButton.tsx
  frontend/src/components/button/Loginbutton.tsx
  frontend/src/components/input/TextInput.tsx
  frontend/styles/pages/members/join.module.scss
  frontend/styles/pages/members/login.module.scss
Labels: enhancement

#24 멘토 / 멘토 신청 / 이상수
  backend/src/main/java/com/example/Main/domain/Member/entity/Member.java
  backend/src/main/java/com/example/Main/domain/Mentor/controller/ApiV1MentorController.java
  backend/src/main/java/com/example/Main/domain/Mentor/dto/MentorDTO.java
  backend/src/main/java/com/example/Main/domain/Mentor/entity/Mentor.java
  backend/src/main/java/com/example/Main/domain/Mentor/entity/MentorMenteeMatching.java
  backend/src/main/java/com/example/Main/domain/Mentor/entity/MentorReview.java
  backend/src/main/java/com/example/Main/domain/Mentor/entity/MentorTechStack.java
  backend/src/main/java/com/example/Main/domain/Mentor/repository/MentorMenteeMatchingRepository.java
  backend/src/main/java/com/example/Main/domain/Mentor/repository/MentorRepository.java
  backend/src/main/java/com/example/Main/domain/Mentor/repository/MentorReviewRepository.java
  backend/src/main/java/com/example/Main/domain/Mentor/request/MentorRegistrationRequest.java
  backend/src/main/java/com/example/Main/domain/Mentor/service/MentorService.java
  backend/src/main/java/com/example/Main/domain/TechStack/dto/TechStackDTO.java
  backend/src/main/java/com/example/Main/domain/TechStack/entity/TechStack.java
  backend/src/main/java/com/example/Main/domain/TechStack/repository/TechStackRepository.java
  backend/src/main/java/com/example/Main/domain/TechStack/request/TechStackAddRequest.java
  backend/src/main/java/com/example/Main/domain/TechStack/service/TechStackService.java
  src/main/java/com/example/Main/domain/Mentor/entity/Mentor.java
Labels: enhancement
